version: '3.9'

services:
  elasticsearch:
    image: elasticsearch:8.2.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kibana:
    image: kibana:8.2.2
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic

  logstash:
    image: logstash:8.2.2
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./logstash_pipeline/
        target: /usr/share/logstash/pipeline
        read_only: true
    networks:
      - elastic
  
volumes:
  es_data:
    driver: local

networks:
  elastic:
    name: elastic
    driver: bridge